name: ci-build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
 
    - name: Restore dependencies
      run: dotnet restore
  
    - name: Test in Debug configuration
      run: dotnet test --no-restore -c Debug --verbosity normal --logger "html;logfilename=${{ github.workspace }}/Tests/TestResults.html"

    - name: Upload test file
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: ${{ github.workspace }}/Tests/TestResults.html
  
    - name: Build in Release configuration
      run: dotnet build --no-restore -c Release     
